name: pyenv
description: Python Version Manager
languages:
  - Python
version: latest
package_name: pyenv
package_names:
  apt: pyenv
  brew: pyenv
  dnf: pyenv
  pacman: pyenv

dependencies:
  - name: make
    type: system
  - name: build-essential
    type: system
  - name: libssl-dev
    type: system
  - name: zlib1g-dev
    type: system
  - name: libbz2-dev
    type: system
  - name: libreadline-dev
    type: system
  - name: libsqlite3-dev
    type: system
  - name: wget
    type: system
  - name: curl
    type: system
  - name: llvm
    type: system
  - name: libncursesw5-dev
    type: system
  - name: xz-utils
    type: system
  - name: tk-dev
    type: system
  - name: libxml2-dev
    type: system
  - name: libxmlsec1-dev
    type: system
  - name: libffi-dev
    type: system
  - name: liblzma-dev
    type: system

post_install:
  - command: curl https://pyenv.run | bash
    description: Install pyenv

shell_config:
  exports:
    PYENV_ROOT: "$HOME/.pyenv"
  path:
    - "$PYENV_ROOT/bin"
  functions:
    pyenv_init: |
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)" 