name: string
description: string
category: string  # Should be "language_manager"
tags: string[]
version: string
homepage: string

# Installation strategy
install:
  pre_install:
    - command: string
      description: string
  post_install:
    - command: string
      description: string
  package_names:
    apt: string
    brew: string
    dnf: string
    pacman: string
  binary:
    url: string
    checksum: string
    extract_path: string
  custom:
    - command: string
      description: string

# Verification strategy
verify:
  command:
    command: string
  expected_output: string
  binary_paths:
    - string
  required_files:
    - string

# Shell configuration
shell_config:
  env:
    key: string
  source:
    - string
  aliases:
    key: string
  functions:
    key: string

# Platform-specific configuration
platform_config:
  linux:
    install:
      # Same structure as install above
  darwin:
    install:
      # Same structure as install above
  windows:
    install:
      # Same structure as install above 