name: fd
description: "A simple, fast and user-friendly alternative to find"
category: "modern"
tags: ["modern", "search", "find", "files"]

package_names:
  apt: fd-find
  brew: fd
  dnf: fd-find
  pacman: fd

version: "latest"
system_dependencies: []
dependencies: []
verify_command: "fd --version"

shell_config:
  aliases:
    find: "fd"  # Replace find with fd
    fdh: "fd --hidden"  # Include hidden files
    fdd: "fd --type d"  # Only directories
    fdf: "fd --type f"  # Only files
    fdl: "fd --type l"  # Only symlinks

  env:
    FD_OPTIONS: "--follow --exclude .git --exclude node_modules"  # Default options

  functions:
    fdsize: |
      fd --type f --exec du -sh {}  # Find files with their sizes
    fdnewer: |
      fd --type f --changed-within ${1:-1d}  # Find files newer than specified time (default 1 day) 