name: fd
description: "A simple, fast and user-friendly alternative to 'find'"
category: "modern"
tags: ["modern", "search", "file", "find"]

package_names:
  apt: fd-find  # Ubuntu/Debian package name is fd-find
  brew: fd
  dnf: fd-find
  pacman: fd

version: "latest"
system_dependencies: []
dependencies: []
verify_command: "which fd && fd --version"

post_install:
  - command: "mkdir -p ~/.local/bin"
    description: "Create local bin directory if it doesn't exist"
  - command: "ln -sf $(which fdfind) ~/.local/bin/fd"
    description: "Create symlink from fdfind to fd"
  - command: "echo 'export PATH=\"$HOME/.local/bin:$PATH\"' >> ~/.bashrc"
    description: "Add local bin to PATH if not already there"

shell_config:
  aliases:
    find: "fd"  # Replace find with fd
    fdi: "fd -i"  # Case-insensitive search
    fdh: "fd -H"  # Include hidden files
    fde: "fd -e"  # Filter by extension

  env:
    FD_OPTIONS: "--follow --exclude .git --exclude node_modules"  # Default options

  functions:
    fdsize: |
      fd-find --type f --exec du -sh {} || fd --type f --exec du -sh {}  # Find files with their sizes
    fdnewer: |
      fd-find --type f --changed-within ${1:-1d} || fd --type f --changed-within ${1:-1d}  # Find files newer than specified time (default 1 day) 