name: lsd
description: "Modern ls command with colors and icons"
category: "modern"
tags: ["modern", "ls", "files", "icons"]

package_names:
  apt: lsd
  brew: lsd
  dnf: lsd
  pacman: lsd

version: "latest"
system_dependencies:
  - cargo  # Required for installation via cargo if package not found

dependencies: []
verify_command: "lsd --version"

post_install:
  - command: "if ! command -v lsd >/dev/null; then cargo install lsd; fi"
    description: "Install lsd via cargo if package not found"
  - command: "mkdir -p ~/.config/lsd"
    description: "Create lsd config directory"

shell_config:
  aliases:
    ls: "lsd"  # Replace ls with lsd
    ll: "lsd -l"  # Long format
    la: "lsd -la"  # Long format including hidden files
    lt: "lsd --tree"  # Tree view
    lta: "lsd --tree -a"  # Tree view with hidden files
    lld: "lsd -l --group-dirs first"  # List with directories first
    llz: "lsd -l --total-size"  # List with total size

  env:
    LS_COLORS: "$(vivid generate molokai)"  # Use vivid for LS_COLORS if available 