name: ripgrep
description: "A search tool that combines the usability of The Silver Searcher with the raw speed of grep"
category: "modern"
tags: ["modern", "search", "grep", "text"]

package_names:
  apt: ripgrep
  brew: ripgrep
  dnf: ripgrep
  pacman: ripgrep

version: "latest"
system_dependencies: []
dependencies: []
verify_command: "which rg && rg --version"

post_install:
  - command: "mkdir -p ~/.config/ripgrep"
    description: "Create ripgrep config directory"
  - command: |
      cat > ~/.config/ripgrep/config << 'EOF'
      --smart-case
      --hidden
      --glob=!.git/*
      --glob=!node_modules/*
      --glob=!target/*
      --glob=!dist/*
      --glob=!build/*
      --glob=!vendor/*
      --glob=!*.min.js
      --glob=!*.min.css
      EOF
    description: "Create ripgrep configuration file"

shell_config:
  aliases:
    rg: "rg --smart-case"  # Enable smart case by default
    rgi: "rg -i"          # Case-insensitive search
    rgf: "rg --files"     # List files
    rgw: "rg --word-regexp"  # Word-regexp search

  env:
    RIPGREP_CONFIG_PATH: "$HOME/.config/ripgrep/config"  # Set config file location

files:
  - source: modern/ripgrep/config
    destination: ~/.config/ripgrep/config
    type: content
    permissions: 0644
    content: |
      # Don't let ripgrep vomit really long lines to my terminal, and show a preview.
      --max-columns=150
      --max-columns-preview
      
      # Add my 'web' type.
      --type-add
      web:*.{html,css,js,ts,jsx,tsx}*
      
      # Using glob patterns to include/exclude files or folders
      --glob=!.git/*
      
      # Set the colors.
      --colors=line:none
      --colors=line:style:bold
      
      # Because who cares about case!?
      --smart-case 