name: ripgrep
description: "Recursively searches directories for a regex pattern while respecting gitignore rules"
category: "modern"
tags: ["modern", "search", "grep", "regex"]

package_names:
  apt: ripgrep
  brew: ripgrep
  dnf: ripgrep
  pacman: ripgrep

version: "latest"
system_dependencies: []
dependencies: []
verify_command: "rg --version"

post_install:
  - command: "mkdir -p ~/.config/ripgrep"
    description: "Create ripgrep config directory"

shell_config:
  aliases:
    grep: "rg"  # Replace grep with ripgrep
    rgh: "rg --hidden"  # Search hidden files
    rgi: "rg -i"  # Case insensitive search
    rgf: "rg -F"  # Fixed-string search (no regex)
    rgc: "rg --count"  # Count matches only

  env:
    RIPGREP_CONFIG_PATH: "$HOME/.config/ripgrep/config"  # Set config file location

files:
  - source: modern/ripgrep/config
    destination: ~/.config/ripgrep/config
    type: content
    permissions: 0644
    content: |
      # Don't let ripgrep vomit really long lines to my terminal, and show a preview.
      --max-columns=150
      --max-columns-preview
      
      # Add my 'web' type.
      --type-add
      web:*.{html,css,js,ts,jsx,tsx}*
      
      # Using glob patterns to include/exclude files or folders
      --glob=!.git/*
      
      # Set the colors.
      --colors=line:none
      --colors=line:style:bold
      
      # Because who cares about case!?
      --smart-case 