name: JetBrains Mono Nerd Font
description: "JetBrains Mono with Nerd Font icons - A developer-focused monospace font"
category: monospace
tags:
  - development
  - programming
  - nerd-font
  - monospace
variants:
  - name: Regular
    weight: "400"
    style: "normal"
    nerd_font: true
  - name: Italic
    weight: "400"
    style: "italic"
    nerd_font: true
  - name: Bold
    weight: "700"
    style: "normal"
    nerd_font: true
  - name: Bold Italic
    weight: "700"
    style: "italic"
    nerd_font: true
download_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip"
install_path: "~/.local/share/fonts"
config_files: []
shell_config:
  env: {}
  path_additions: []
requires_restart: true 