name: Node.js
description: "JavaScript runtime built on Chrome's V8 JavaScript engine"
category: interpreted
tags:
  - programming
  - development
  - web-development
  - javascript
version: "20"
package_names:
  default: nodejs
  apt: nodejs
  dnf: nodejs
  pacman: nodejs
  brew: node
system_dependencies:
  - build-essential
  - curl
dependencies: []
verify_command: node --version
post_install: []
shell_config:
  aliases:
    node: node
    npm: npm
  functions: {}
  env:
    NODE_ENV: "development"
  path_additions:
    - "${HOME}/.local/bin"
config_files:
  - source: |
      registry=https://registry.npmjs.org/
      save-exact=true
    destination: ~/.npmrc
    type: content
    permissions: "0644"
package_manager:
  name: npm
  install_command: "npm install -g"
  global_packages:
    - typescript
    - ts-node
    - nodemon
    - yarn
    - pnpm
version_manager:
  name: nvm
  install_command: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  versions:
    - "20.11.1"
    - "18.19.1"
    - "16.20.2"
  global_version: "20.11.1"
  post_install:
    - nvm use 20.11.1
  shell_config:
    aliases:
      nvm: "nvm"
    functions:
      nvm-init: |
        function nvm-init() {
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        }
    env:
      NVM_DIR: "${HOME}/.nvm"
    path_additions: []
requires_restart: true 