# Tool Configuration Schema
type: object
required:
  - name
  - package_names
  - version
  - description
  - category
  - tags
  - system_dependencies
  - dependencies
  - verify_command
  - post_install
  - shell_config
properties:
  name:
    type: string
    description: "The name of the tool"
  package_names:
    type: object
    description: "Package names for different package managers"
    properties:
      apt:
        type: string
      dnf:
        type: string
      pacman:
        type: string
      brew:
        type: string
  version:
    type: string
    description: "Version constraint for the package"
  description:
    type: string
    description: "A brief description of the tool"
  category:
    type: string
    description: "Category of the tool (e.g., modern-cli, development, etc.)"
  tags:
    type: array
    items:
      type: string
    description: "Tags for categorizing and searching"
  system_dependencies:
    type: array
    items:
      type: string
    description: "System-level dependencies required for installation"
  dependencies:
    type: array
    items:
      type: string
    description: "Other tools that this tool depends on"
  verify_command:
    type: string
    description: "Command to verify successful installation"
  post_install:
    type: array
    items:
      type: object
      properties:
        command:
          type: string
    description: "Commands to run after installation"
  shell_config:
    type: object
    properties:
      aliases:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              type: string
      functions:
        type: object
        additionalProperties:
          type: string
      env:
        type: object
        additionalProperties:
          type: string
    description: "Shell configuration to apply after installation"
  package_name:
    type: string
    description: "Default package name"
  path_additions:
    type: array
    items:
      type: string
    description: "PATH additions"
  config_files:
    type: array
    items:
      type: object
      properties:
        source:
          type: string
          description: "Source path or content"
        destination:
          type: string
          description: "Target path"
        type:
          type: string
          description: "file, symlink, or content"
        permissions:
          type: string
          description: "File permissions (e.g., '0644')"
    description: "Configuration files to create/symlink"
  requires_restart:
    type: boolean
    description: "Whether shell restart is needed" 