linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - goimports

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - build/
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    min-confidence: 0.8
  gosec:
    excludes:
      - G404  # Insecure random number source (math/rand) 