name: "JetBrains Mono Nerd Font"
description: "A monospace font with programming ligatures and Nerd Font icons"
category: "programming"
tags: ["monospace", "programming", "nerd-font"]

source: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip"
system_dependencies:
  - unzip
  - curl

install:
  - "mkdir -p ~/.local/share/fonts"
  - "curl -L -o /tmp/JetBrainsMono.zip ${source}"
  - "unzip -o /tmp/JetBrainsMono.zip -d ~/.local/share/fonts/"
  - "fc-cache -f"

verify:
  - "fc-list | grep -i 'JetBrains Mono'" 