name: "JetBrains Mono Nerd Font"
description: "A monospace font with programming ligatures and Nerd Font icons"
category: "programming"
tags: ["monospace", "programming", "nerd-font"]

source: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip"
system_dependencies:
  - unzip
  - curl

install:
  - command: "mkdir -p ~/.local/share/fonts"
    description: "Create fonts directory"
  - command: "curl -L -o /tmp/JetBrainsMono.zip ${source}"
    description: "Download font"
  - command: "unzip -o /tmp/JetBrainsMono.zip -d ~/.local/share/fonts/"
    description: "Extract font files"
  - command: "fc-cache -f"
    description: "Update font cache"

verify:
  - command: "fc-list | grep -i 'JetBrains Mono'"
    description: "Verify font is installed" 