name: lsd
package_names:
  default: lsd
  apt: lsd
  dnf: lsd
  pacman: lsd
  brew: lsd
version: latest
description: "Next-gen ls command with colors and icons"
category: modern
tags:
  - file-manager
  - terminal
  - productivity
system_dependencies: []
dependencies: []
verify_command: lsd --version
post_install: []
shell_config:
  aliases:
    ls: lsd
    ll: lsd -l
    la: lsd -la
  functions: {}
  env: {}
  path_additions: []
config_files: []
requires_restart: false 