# Dotfiles Configuration Schema
name: string  # Name of the dotfiles set
description: string  # Description of the dotfiles set
category: string  # Category (shell, editor, terminal, etc.)
tags:  # List of tags for searching/filtering
  - string
files:  # List of dotfiles to manage
  - source: string  # Source path or content
    destination: string  # Target path (relative to $HOME)
    type: string  # file, symlink, or content
    permissions: string  # File permissions (e.g., "0644")
    backup: boolean  # Whether to backup existing file
    backup_suffix: string  # Suffix for backup files (e.g., ".bak")
dependencies:  # Dependencies required for these dotfiles
  - string
shell_config:  # Shell-specific configuration
  aliases:  # Shell aliases
    string: string  # alias: command
  functions:  # Shell functions
    string: string  # function_name: function_body
  env:  # Environment variables
    string: string  # variable: value
  path_additions:  # PATH additions
    - string
post_install:  # Commands to run after installation
  - string
requires_restart: boolean  # Whether shell restart is needed 