name: Go
description: Go programming language
category: language
tags: ["go", "golang", "runtime"]
version: "1.21"
installer: goenv
verify_command: go version

# Dependencies
dependencies:
  - name: goenv
    type: package
    optional: false

package_names:
  apt: golang-go
  brew: go
  dnf: golang
  pacman: go

post_install:
  - command: goenv install 1.21
    description: Install Go 1.21 using goenv
  - command: goenv global 1.21
    description: Set Go 1.21 as the global version

shell_config:
  env:
    GOENV_ROOT: "$HOME/.goenv"
    PATH: "$GOENV_ROOT/bin:$PATH"
  source:
    - "eval \"$(goenv init -)\"" 