name: Node.js
description: JavaScript runtime
category: language
tags: ["javascript", "runtime"]
version: "18"
installer: nvm
verify_command: node --version

# Dependencies
dependencies:
  - name: nvm
    type: package
    optional: false

package_names:
  apt: nodejs
  brew: node
  dnf: nodejs
  pacman: nodejs

post_install:
  - command: nvm install 18
    description: Install Node.js 18 using nvm
  - command: nvm use 18
    description: Set Node.js 18 as the active version

shell_config:
  env:
    NVM_DIR: "$HOME/.nvm"
  source:
    - "$HOME/.nvm/nvm.sh"
    - "$HOME/.nvm/bash_completion" 