name: Python
description: Python programming language
category: language
tags: ["python", "runtime"]
version: "3.11"
installer: pyenv
verify_command: python --version

# Dependencies
dependencies:
  - name: pyenv
    type: package
    optional: false

# System dependencies required for building Python
system_dependencies:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev

package_names:
  apt: python3
  brew: python
  dnf: python3
  pacman: python

post_install:
  - command: pyenv install 3.11
    description: Install Python 3.11 using pyenv
  - command: pyenv global 3.11
    description: Set Python 3.11 as the global version

shell_config:
  env:
    PYENV_ROOT: "$HOME/.pyenv"
    PATH: "$PYENV_ROOT/bin:$PATH"
  source:
    - "eval \"$(pyenv init -)\""
    - "eval \"$(pyenv virtualenv-init -)\"" 