name: Curl
description: "Command-line tool for transferring data"
category: "essential"
tags: ["network", "http", "essential"]
package_names:
  apt: curl
  brew: curl
  dnf: curl
  pacman: curl
version: "latest"
system_dependencies: []
dependencies: []
verify_command: "curl --version"
post_install: []
shell_config:
  aliases: {}
  functions: {}
  env: {}

files:
  - source: network/curl-format
    destination: ~/.dotfiles/network/curl-format
    type: content
    permissions: 0644 