name: Wget
description: "Command-line utility for downloading files"
category: "essential"
tags: ["network", "download", "essential"]
package_names:
  apt: wget
  brew: wget
  dnf: wget
  pacman: wget
version: "latest"
system_dependencies: []
dependencies: []
verify_command: "wget --version"
post_install: []
shell_config:
  aliases: {}
  functions: {}
  env: {} 