name: tool
description: Schema for tool configuration files
type: object
required:
  - name
  - description
  - category
  - package_names
properties:
  name:
    type: string
    description: Name of the tool
  description:
    type: string
    description: Description of the tool
  category:
    type: string
    description: Category of the tool (e.g., modern, essential)
  tags:
    type: array
    items:
      type: string
    description: Tags for categorizing the tool
  package_names:
    type: object
    description: Package names for different package managers
    properties:
      apt:
        type: string
      brew:
        type: string
      dnf:
        type: string
      pacman:
        type: string
  version:
    type: string
    description: Version of the tool to install
  system_dependencies:
    type: array
    items:
      type: string
    description: System dependencies required by the tool
  dependencies:
    type: array
    items:
      type: string
    description: Other tools required by this tool
  verify_command:
    type: string
    description: Command to verify successful installation
  post_install:
    type: array
    items:
      type: object
      properties:
        command:
          type: string
        description:
          type: string
      required:
        - command
        - description
    description: Commands to run after installation
  shell_config:
    type: object
    description: Shell configuration for the tool
    properties:
      aliases:
        type: object
        additionalProperties:
          type: string
        description: Shell aliases for the tool
      functions:
        type: object
        additionalProperties:
          type: string
        description: Shell functions for the tool
      env:
        type: object
        additionalProperties:
          type: string
        description: Environment variables for the tool
  files:
    type: array
    items:
      type: object
      properties:
        source:
          type: string
        destination:
          type: string
        type:
          type: string
        permissions:
          type: integer
        content:
          type: string
      required:
        - source
        - destination
    description: Files to be created or copied 